llm_config:
  base_url: https://api.deepseek.com/
  api_key: sk-088bd7c594cf415e90f0139e6f9cf908
  model_name: deepseek-reasoner
  temperature: 0.7
  max_tokens: 8192
agent_config:
  max_iterations: 100
  max_retries: 3
  max_search_results: 10
mcp_config:
  mcpServers:
    amap-maps-streamableHTTP:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.amap.com/mcp?key=00b05640cc55c0ba2b7f85e0b3f2e6e7
      headers: null
    jina-mcp-server:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.jina.ai/v1
      headers:
        Authorization: Bearer jina_133c673d569840d3b1e379a526eee6d4VKMVBI9J5HYE2xd4ys7i6ehZUNb6
a2a_config:
  a2a_servers: [ ]
